backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "./images/uploads" # Media files will be stored in the repo under images/uploads
# media_folder: "../public/thumbs" # Media files will be stored in the repo under static/images/uploads
# public_folder: "./images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "projects"
    label: "Blog"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Stack", name: "stack", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "thumb", widget: "image"}
      - {label: "Image", name: "feature", widget: "image"}
        